extends:
  - stylelint-config-standard
rules:
  # Disallow custom colors as these don't work well with dark mode.
  # Use PF semantic tokens instead:
  # https://www.patternfly.org/tokens/all-patternfly-tokens
  color-named: never
  color-no-hex: true
  function-disallowed-list:
    - rgb
    - rgba
    - hsl
    - hsla
    - oklch
    - oklch
    - hwb
    - lab
    - lch
  # PatternFly CSS vars don't conform to stylelint's regex. Disable this rule.
  custom-property-pattern: null
  # Disable the standard rule to allow BEM-style class names with underscores.
  selector-class-pattern: null
  # Disallow CSS class names prefixed with .pf- or .co- as these prefixes are
  # reserved by PatternFly and OpenShift console.
  selector-disallowed-list:
    - "*"
    - /\.(pf|co)-/
  # Plugins should avoid naked element selectors like `table` and `li` since
  # this can impact layout of existing pages in console.
  selector-max-type:
    - 0
    - ignore:
        - compounded
        - descendant
